drop table if exists products;
create table products(
id GENERATED BY DEFAULT AS IDENTITY primary key,
name varchar(100),
price int,
discountType int
);
drop table if exists discount_cards;
create table discount_cards(
id GENERATED BY DEFAULT AS IDENTITY primary key,
number int unique,
discount int
);
